config/routes.rb
Prova4::Application.routes.draw do
  resources :clientes

  resources :posts

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
validates :Nome, :presence => { :message => 'nao pode ser nulo' }
validates :Nome, :format => { :with => /\A[a-zA-Z]+\z/, :message=>'tem que ter so letras' } 
validates :CPF, :presence => { :message => 'nao pode ser nulo' }
validates :CPF, :length => { :is => 11, :message=>'tem que ter 11 digitos' } 
validates :CPF, :format => { :with => /\A[+-]?\d+\Z/, :message=>'tem que ter so numeros' } 
validates :Telefone, :presence => { :message => 'nao pode ser nulo' }
validates :Telefone, :format => { :with => /\A[+-]?\d+\Z/, :message=>'tem que ter so numeros' } 
validates :Telefone, :length => { :is => 8, :message=>'tem que ter 8 digitos' } 
validates :Email, :presence => { :message => 'nao pode ser nulo' }
validates :Email, :format => { :with => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/, :message=>'Isso nao parece um email' } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente cadastrado com sucesso' }
        format.json { render action: 'show', status: :created, location: @cliente }
      else
        format.html { render action: 'new' }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente editado com sucesso' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:Nome, :CPF, :DataNascimento, :Email, :Endereco, :Telefone)
    end
end

app/controllers/controle_controller.rb
class ControleController < ApplicationController
   def index
      @helloworld = "Hello world!!!"
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nome %><br>
    <%= f.text_field :Nome %>
  </div>
  <div class="field">
    <%= f.label :CPF %><br>
    <%= f.text_field :CPF %>
  </div>
  <div class="field">
    <%= f.label :"Data de Nascimento" %><br>
    <%= f.date_select :DataNascimento, :order => [:day, :month, :year], :start_year =>  Time.now.year - 110, :end_year =>  Time.now.year %>
  </div>
  <div class="field">
    <%= f.label :Email %><br>
    <%= f.text_field :Email %>
  </div>
  <div class="field">
    <%= f.label :Endereco %><br>
    <%= f.text_field :Endereco %>
  </div>
  <div class="field">
    <%= f.label :Telefone %><br>
    <%= f.text_field :Telefone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editar cliente</h1>

<%= render 'form' %>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<div class="link">


<%= link_to 'Voltar', clientes_path %>
</div>

app/views/clientes/index.html.erb
<h1>Lista de Clientes Cadastrados</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th>Data de Nascimento</th>
      <th>Email</th>
      <th>Endereco</th>
      <th>Telefone</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.Nome %></td>
        <td><%= cliente.CPF %></td>
        <td><%= cliente.DataNascimento %></td>
        <td><%= cliente.Email %></td>
        <td><%= cliente.Endereco %></td>
        <td><%= cliente.Telefone %></td>
        <td><%= link_to 'Mostrar', cliente %></td>
        <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Deletar', cliente, method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="link">
<%= link_to 'Novo Cliente', new_cliente_path %>
</div>

app/views/clientes/new.html.erb
<h1>New cliente</h1>

<%= render 'form' %>
<div class="link">
<%= link_to 'Voltar', clientes_path %>
</div>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cliente.Nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @cliente.CPF %>
</p>

<p>
  <strong>Datanascimento:</strong>
  <%= @cliente.DataNascimento %>
</p>

<p>
  <strong>Email:</strong>
  <%= @cliente.Email %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @cliente.Endereco %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @cliente.Telefone %>
</p>
<div class="link">
<%= link_to 'Editar', edit_cliente_path(@cliente) %>
</div> 
<div class="link">
<%= link_to 'Voltar', clientes_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prova4</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/index.erb
<%= @helloworld %>